#!/bin/bash

#All CPUs active and work at the maximum freq
echo 0 > /sys/devices/system/cpu/cpuquiet/tegra_cpuquiet/enable
echo 1 > /sys/devices/system/cpu/cpu0/online
echo 1 > /sys/devices/system/cpu/cpu1/online
echo 1 > /sys/devices/system/cpu/cpu2/online
echo 1 > /sys/devices/system/cpu/cpu3/online
echo "userspace" > /sys/devices/system/cpu/cpu0/cpufreq/scaling_governor

echo 2320500000 > /sys/devices/system/cpu/cpu0/cpufreq/scaling_setspeed
echo 2320500000 > /sys/devices/system/cpu/cpu1/cpufreq/scaling_setspeed
echo 2320500000 > /sys/devices/system/cpu/cpu2/cpufreq/scaling_setspeed
echo 2320500000 > /sys/devices/system/cpu/cpu3/cpufreq/scaling_setspeed
